#!/bin/sh

PRG=$0

while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
        PRG="$link"
    else
        PRG="`dirname "$PRG"`/$link"
    fi
done

progdir=`dirname "$PRG"`

JAVACMD="$progdir/../Plugins/openjdk-13.0.1.jdk/Contents/Home/bin/java"

exec "$JAVACMD" -jar "$progdir/../Java/transaction-dl-0.1.0.jar" \
       -Dapple.laf.useScreenMenuBar=true
