package info.hildegynoid.transaction

import info.hildegynoid.BuildConfig
import info.hildegynoid.transaction.ui.Controller
import javafx.application.Application
import javafx.application.Platform
import javafx.fxml.FXMLLoader
import javafx.scene.Parent
import javafx.scene.Scene
import javafx.stage.Stage
import org.koin.Logger.slf4jLogger
import org.koin.core.context.startKoin
import org.koin.core.logger.Level
import org.slf4j.bridge.SLF4JBridgeHandler

class MyApplication : Application() {

    override fun init() {
        // jul to slf4j
        SLF4JBridgeHandler.removeHandlersForRootLogger()
        SLF4JBridgeHandler.install()

        startKoin {
            slf4jLogger(Level.INFO)
            modules(myModule)
        }
    }

    override fun start(stage: Stage) {
        val resource = javaClass.classLoader.getResource("fxml/main.fxml")
        val loader = FXMLLoader(resource)
        val parent = loader.load<Parent>()
        stage.scene = Scene(parent, 450.0, 400.0)
        stage.title = getTitle() + " Version." + getVersion()
        stage.show()

        val controller = loader.getController<Controller>()

        stage.showingProperty().addListener { _, oldValue, newValue ->
            if (oldValue == true && newValue == false) {
                controller.shutdown()
                Platform.exit()
            }
        }
    }

    override fun stop() {
        Platform.exit()
    }

    // BuildConfig class generated by `generateBuildConfig` task
    private fun getTitle(): String = BuildConfig.TITLE
    private fun getVersion(): String = BuildConfig.VERSION
}
